export default function Experience() {
	const experiences = [
		{
			id: 0,
			company: 'Liblab',
			title: 'Software Engineer',
			startDate: new Date('04/2023'),
			endDate: new Date('10/2023'),
			stack: ['Python', 'Langchain', 'Node.js'],
			accomplishments: [
				`Built an AI service to document company autogenerated SDK's using Python and Langchain`,
				`Added feature to Node.js CLI that allowed creating automatic PR's on Github`
			]
		},
		{
			id: 1,
			company: 'Team Liquid',
			title: 'Sr. Backend Developer',
			startDate: new Date('01/2022'),
			endDate: new Date('04/2023'),
			stack: ['Node.js', 'PostgreSQL', 'MongoDB', 'Redis', 'Sequelize', 'Docker', 'Nginx', 'React', 'Redux'],
			accomplishments: [
				`Created a private NPM package to handle backend Localization`,
				`Maintained Node.js monolith backend to improve error handling and add translation support`,
				`Maintained React APP with over 110k users`,
			]
		},
		{
			id: 2,
			company: 'Soft',
			title: 'Backend Developer',
			startDate: new Date('06/2021'),
			endDate: new Date('12/2021'),
			stack: ['Node.js', 'Nest.js', 'GraphQL', 'Redis', 'RabbitMQ', 'PostgreSQL', 'CASL', 'Nginx'],
			accomplishments: [
				`Created authentication and user managements services for a backend using microservice architecture in Nest.js`,
				`Fixed critical database failure that existed in all company projects in PostgreSQL`,
				`Architected docker networks to make them more reliable and secure`,
				`Developed GraphQL backend applications with cache, sockets and more`
			]
		},
		{
			id: 3,
			company: 'CGEE',
			title: 'Senior Fullstack Developer',
			startDate: new Date('07/2016'),
			endDate: new Date('06/2021'),
			stack: ['Node.js', 'MongoDB', 'Angular+', 'Java', 'SpringMVC', 'PostgreSQL', 'Vue', 'd3'],
			accomplishments: [
				`Created ISurvey, a CMS to plan, release and monitor surveys using Angular and Node.js`,
				`Maintained legacy Java application for managing contracts`,
				`Created data visualization interfaces using Vue and d3`
			]
		},
	]
	return (
		<section
			id='experience'
			className="flex flex-col items-center justify-stretch w-full h-full max-h-full p-4 bg-light text-dark-1"
		>
			<div className='flex flex-col min-w-fit md:w-fit justify-center max-h-full items-center mb-2 md:mb-0'>
				<h2 className="text-3xl mb-4">Experience</h2>

				<div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-h-full overflow-auto rounded-lg">
					{
						experiences.map((experience) => (
							<div
								key={experience.id}
								className="block p-2 basis-1/3 h-[400px] min-w-[200px] shadow-lg bg-highlight text-dark-1 rounded-md  overflow-y-auto"
							>
								<h3>{experience.company}</h3>
								<h4>{experience.title}</h4>
								{
									experience.accomplishments.map((text, i) => (<p key={i}>{text}</p>))
								}
								<div className="flex flex-row flex-wrap">
									{
										experience.stack.map((text, i) => (<span key={i}>{text}</span>))
									}

								</div>
							</div>
						))
					}
				</div>
			</div>
		</section>
	)
}
